name: forecasting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - altair
  - jupyter
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pytorch
  - scipy
  - scikit-learn
  - torchvision
  - xgboost



